In [1]:
NumPy is essential for performing high-performance numerical computations.

It provides a powerful N-dimensional array object, making it easier to manipulate large datasets and perform mathematical operations.

Its vectorization capabilities and memory efficiency make it the go-to library for scientific computing and data science.

It integrates well with other libraries like Pandas, SciPy, and Scikit-learn, which are widely used in data analysis and machine learning.

SyntaxError: invalid syntax (3436364396.py, line 1)

In [59]:
import numpy as np
a = np.array([1, 2, 3, 4, 5])
print(a)


[1 2 3 4 5]


In [5]:
import numpy as np
b = np.array([[1, 2, 3], [4, 5, 6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [57]:
import numpy as np
c = np.zeros((2, 3)) 
print(c)


[[0. 0. 0.]
 [0. 0. 0.]]


In [11]:
import numpy as np
d = np.ones((3, 2))  # Creates a 3x2 array of ones
print(d)


[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [13]:
import numpy as np
e = np.arange(0, 10, 2)  # Creates an array with values from 0 to 10, stepping by 2
print(e)


[0 2 4 6 8]


In [15]:
import numpy as np
f = np.linspace(0, 1, 5)  # Creates an array of 5 evenly spaced values between 0 and 1
print(f)


[0.   0.25 0.5  0.75 1.  ]


In [17]:
import numpy as np
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

# Addition
print(x + y)

# Subtraction
print(x - y)

# Element-wise multiplication
print(x * y)

# Element-wise division
print(x / y)


[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


In [19]:
import numpy as np
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
# Adding a scalar value to an array
print(x + 5)

# Multiplying an array by a scalar
print(x * 3)


[6 7 8]
[3 6 9]


In [21]:
g = np.array([1, 2, 3, 4, 5, 6])
reshaped = g.reshape(2, 3)  # Reshape to 2 rows and 3 columns
print(reshaped)


[[1 2 3]
 [4 5 6]]


In [23]:
h = np.array([[1, 2, 3], [4, 5, 6]])
flattened = h.flatten()  # Convert the 2D array to a 1D array
print(flattened)


[1 2 3 4 5 6]


In [25]:
i = np.array([[1, 2], [3, 4], [5, 6]])
transposed = i.T  # Transpose of the matrix (flip rows and columns)
print(transposed)


[[1 3 5]
 [2 4 6]]


In [27]:
a = np.array([1, 2, 3, 4, 5])
print(a[2])  # Access the third element


3


In [29]:
b = np.array([[1, 2, 3], [4, 5, 6]])
print(b[0, 1])  # Access element in the first row, second column


2


In [31]:
c = np.array([1, 2, 3, 4, 5])
print(c[1:4])  # Get a slice of the array from index 1 to 3


[2 3 4]


In [33]:
d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(d[0:2, 1:3])  # Slice the first two rows and the second and third columns


[[2 3]
 [5 6]]


In [35]:
e = np.array([1, 2, 3, 4])
print(np.sum(e))  # Sum of all elements


10


In [37]:
f = np.array([1, 2, 3, 4, 5])
print(np.mean(f))  # Mean of the array
print(np.std(f))  # Standard deviation of the array


3.0
1.4142135623730951


In [39]:
g = np.array([[1, 2], [3, 4]])
h = np.array([[5, 6], [7, 8]])
print(np.dot(g, h))  # Matrix multiplication


[[19 22]
 [43 50]]


In [41]:
i = np.array([1, 4, 9, 16])
print(np.sqrt(i))  # Square root of each element


[1. 2. 3. 4.]


In [43]:
j = np.random.rand(3)  # Generate 3 random numbers between 0 and 1
print(j)


[0.88927824 0.56743712 0.70809181]


In [45]:
k = np.random.randint(0, 10, size=(2, 3))  # Generate random integers between 0 and 10 in a 2x3 array
print(k)


[[7 3 5]
 [4 5 5]]


In [47]:
l = np.random.randn(3, 2)  # Generate 3x2 array from a normal distribution
print(l)


[[-0.37144322  0.59626353]
 [-0.49461208  0.73166685]
 [-0.28999389 -0.05428357]]


In [49]:
m = np.array([1, 2, 3, 4, 5])
print(np.min(m))  # Minimum value
print(np.max(m))  # Maximum value
print(np.argmax(m))  # Index of the maximum value
print(np.argmin(m))  # Index of the minimum value


1
5
4
0


In [51]:
n = np.array([[1, 2], [3, 4], [5, 6]])
print(np.sum(n, axis=0))  # Sum along the columns
print(np.sum(n, axis=1))  # Sum along the rows


[ 9 12]
[ 3  7 11]


In [53]:
o = np.array([[1, 2], [3, 4]])
print(np.linalg.inv(o))  # Inverse of a matrix


[[-2.   1. ]
 [ 1.5 -0.5]]


In [55]:
A = np.array([[3, 1], [1, 2]])
b = np.array([9, 8])
x = np.linalg.solve(A, b)  # Solve Ax = b
print(x)


[2. 3.]


In [61]:
# 1D array
a = np.array([1, 2, 3, 4, 5])
print(a.size)  # Output: 5 (5 elements in the array)

# 2D array
b = np.array([[1, 2, 3], [4, 5, 6]])
print(b.size)  # Output: 6 (6 elements in total)

# 3D array
c = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(c.size)  # Output: 12 (12 elements in total)


5
6
8


In [63]:
# 1D array
a = np.array([1, 2, 3, 4, 5])
print(a.shape)  # Output: (5,) (5 elements in 1D)

# 2D array
b = np.array([[1, 2, 3], [4, 5, 6]])
print(b.shape)  # Output: (2, 3) (2 rows, 3 columns)

# 3D array
c = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(c.shape)  # Output: (2, 2, 2) (2 matrices, 2 rows, 2 columns in each)


(5,)
(2, 3)
(2, 2, 2)


In [65]:
# 1D array with integers
a = np.array([1, 2, 3, 4, 5])
print(a.dtype)  # Output: int64 (depends on the system architecture)

# 1D array with floating point numbers
b = np.array([1.0, 2.5, 3.8, 4.2])
print(b.dtype)  # Output: float64

# 1D array with complex numbers
c = np.array([1+2j, 3+4j, 5+6j])
print(c.dtype)  # Output: complex128


int32
float64
complex128
