In [17]:
arrays concatination

axis 0 = rows
axis 1 = columns

finding dimention of arrays , 1d , 2d , 3d
arr.shape
np.reshape
see other optional parameters of reshape
order c = used to populate row first
order f = used to populate column first
np.arrange(6)

row vector 
column vector

expand dimension

indexing and slicing of arary

np.vstack(arr1,arr2) = for vertical stack
np.hstack(arr1,arr2) = for horizontal stack

np.hsplit(arr1,3) = for horizontal split

copy arr
insert and append
sorting array in ascending and decending order
NumPy Array Reshaping
NumPy Splitting Array
NumPy Array Copy vs View

deleting element from array

generating ones and zeros and random elements in array

finding unique values in array through unique function , 
also can find indices of unique numbers

transpose 

flipfunction use to flip array

flatten function converts other dimentions to one dimention array

reval()

ploting array

SyntaxError: invalid decimal literal (545684866.py, line 6)

In [21]:
import copy
import numpy as np

original_list = [[1, 2, 3], [4, 5, 6]]

# Shallow Copy
shallow_list = copy.copy(original_list)
shallow_list[0][0] = 99  # Modifying nested list affects the original

# Deep Copy
deep_list = copy.deepcopy(original_list)
deep_list[1][1] = 88  # No effect on original

print("Original List:", original_list)
print("Shallow Copy:", shallow_list)
print("Deep Copy:", deep_list)

print("\n" + "="*40 + "\n")  # Separator

# ====== Shallow vs Deep Copy for NumPy Arrays ======
original_array = np.array([1, 2, 3])

# Shallow Copy using view()
shallow_array = original_array.view()
shallow_array[0] = 99  # Affects original array

# Deep Copy using copy()
deep_array = original_array.copy()
deep_array[1] = 88  # Does NOT affect original

print("Original Array:", original_array)
print("Shallow Copy:", shallow_array)
print("Deep Copy:", deep_array)


Original List: [[99, 2, 3], [4, 5, 6]]
Shallow Copy: [[99, 2, 3], [4, 5, 6]]
Deep Copy: [[99, 2, 3], [4, 88, 6]]


Original Array: [99  2  3]
Shallow Copy: [99  2  3]
Deep Copy: [99 88  3]


In [15]:
import numpy as np

# Define the matrix
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

# Find the numbers greater than 5
greater_than_5 = matrix[matrix > 5]

# Output the result
print("Numbers greater than 5:", greater_than_5)
print("Count of numbers greater than 5:", greater_than_5.size)


Numbers greater than 5: [6 7 8 9]
Count of numbers greater than 5: 4


In [13]:
import numpy as np

# Define the matrix
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

# Find the minimum value in each row
row_min = np.min(matrix, axis=1)

# Output the result
print("Minimum value in each row:", row_min)


Minimum value in each row: [1 4 7]


In [5]:
import numpy as np

# Define the matrix
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

# Row-wise addition
row_sum = matrix.sum(axis=1)

# Column-wise addition
col_sum = matrix.sum(axis=0)

# Output results
print("Row-wise sum:", row_sum)
print("Column-wise sum:", col_sum)


Row-wise sum: [ 6 15 24]
Column-wise sum: [12 15 18]


In [11]:
import numpy as np

# Define the matrix
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

# Find the maximum value in each column
column_max = np.max(matrix, axis=0)

# Output the result
print("Maximum value in each column:", column_max)


Maximum value in each column: [7 8 9]


In [7]:
import numpy as np
arr = np.array([5, 10, 15, 20, 25]) 
a = arr[3] 
print(a)


20


In [9]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6])
sub_array = arr[:4] 
print(sub_array)


[1 2 3 4]


In [11]:
import numpy as np
arr = np.array([7, 8, 9, 10])  
reshaped_arr = arr.reshape(1, 4) 
print(reshaped_arr)
print("Shape of the array:", reshaped_arr.shape) 


[[ 7  8  9 10]]
Shape of the array: (1, 4)


In [33]:
import numpy as np
arr = np.array([11, 12, 13, 14])  

arr_2d = np.expand_dims(arr, axis=1) 

print(arr_2d)
print("Shape of the array:", arr_2d.shape) 


[[11]
 [12]
 [13]
 [14]]
Shape of the array: (4, 1)


In [27]:
import numpy as np
arr = np.array([12,24,36,48,60])
sub_array = arr[:4] 
sub_array[0]=99
print(sub_array)
print(arr)

[99 24 36 48]
[99 24 36 48 60]


In [29]:
import numpy as np

arr = np.array([1, 3, 5])
arr = np.append(arr, [2, 9])  
arr = np.insert(arr, 1, 4)   

print(arr)


[1 4 3 5 2 9]


In [3]:
a=10
b="sadam"
print(a , b)

10 sadam


In [21]:
import numpy as np

arr = np.array([30, 10, 50, 20, 40])

ascending_sorted = np.sort(arr)
print("Ascending Order:", ascending_sorted)

descending_sorted = np.sort(arr)[::-1]
print("Descending Order:", descending_sorted)

Ascending Order: [10 20 30 40 50]
Descending Order: [50 40 30 20 10]


In [25]:
import numpy as np

arr = np.array([15, 25, 35, 45, 55])

arr = arr[arr != 35]
print("After removing 35:", arr)

arr = np.delete(arr, 2)
print("After deleting index 2:", arr)


After removing 35: [15 25 45 55]
After deleting index 2: [15 25 55]


In [29]:
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

result1 = np.concatenate((arr1, arr2))
print("Concatenated Array:", result)


arr3 = np.array([7,8,9])

result2 = np.concatenate((result1, arr3))
print("Concatenated Array:", result2)

Concatenated Array: [1 2 3 4 5 6]
Concatenated Array: [1 2 3 4 5 6 7 8 9]


In [34]:
import numpy as np

arr1 = np.array([10, 20, 30, 40, 50, 60])

split_arrays = np.split(arr1, 3)

print(split_arrays)


[array([10, 20]), array([30, 40]), array([50, 60])]


In [42]:
import numpy as np

arr1 = np.array([100, 200, 300, 400, 500, 600])

arr2 = np.copy(arr1)

arr2[-1] = 99

print("Original Array (arr1):", arr1)
print("Copied Array (arr2):", arr2)

arr1 = np.concatenate((arr1, [700, 800]))

print("Array after appending 700 and 800:", arr1)

arr1 = np.insert(arr1, 1, 250)

print("Final Array:", arr1)


Original Array (arr1): [100 200 300 400 500 600]
Copied Array (arr2): [100 200 300 400 500  99]
Array after appending 700 and 800: [100 200 300 400 500 600 700 800]
Final Array: [100 250 200 300 400 500 600 700 800]


In [44]:
import numpy as np

arr1 = np.array([100, 250, 200, 300, 400, 500, 600, 700, 800])


print("Original Array:", arr1)

arr1_sorted = np.sort(arr1)

print("Sorted Array (Ascending):", arr1_sorted)


Original Array: [100 250 200 300 400 500 600 700 800]
Sorted Array (Ascending): [100 200 250 300 400 500 600 700 800]


In [48]:
import numpy as np

arr1 = np.array([100, 200, 300, 400, 500, 600])

print("Original Array:", arr1)

split_arrays = np.split(arr1, 2)

print(split_arrays)


Original Array: [100 200 300 400 500 600]
[array([100, 200, 300]), array([400, 500, 600])]
