In [ ]:
arrays concatination

axis 0 = rows
axis 1 = columns

finding dimention of arrays , 1d , 2d , 3d
arr.shape
np.reshape
see other optional parameters of reshape
order c = used to populate row first
order f = used to populate column first
np.arrange(6)

row vector 
column vector

expand dimension

indexing and slicing of arary

np.vstack(arr1,arr2) = for vertical stack
np.hstack(arr1,arr2) = for horizontal stack

np.hsplit(arr1,3) = for horizontal split

copy arr
insert and append
sorting array in ascending and decending order
NumPy Array Reshaping
NumPy Splitting Array
NumPy Array Copy vs View

deleting element from array

In [21]:
import copy
import numpy as np

original_list = [[1, 2, 3], [4, 5, 6]]

# Shallow Copy
shallow_list = copy.copy(original_list)
shallow_list[0][0] = 99  # Modifying nested list affects the original

# Deep Copy
deep_list = copy.deepcopy(original_list)
deep_list[1][1] = 88  # No effect on original

print("Original List:", original_list)
print("Shallow Copy:", shallow_list)
print("Deep Copy:", deep_list)

print("\n" + "="*40 + "\n")  # Separator

# ====== Shallow vs Deep Copy for NumPy Arrays ======
original_array = np.array([1, 2, 3])

# Shallow Copy using view()
shallow_array = original_array.view()
shallow_array[0] = 99  # Affects original array

# Deep Copy using copy()
deep_array = original_array.copy()
deep_array[1] = 88  # Does NOT affect original

print("Original Array:", original_array)
print("Shallow Copy:", shallow_array)
print("Deep Copy:", deep_array)


Original List: [[99, 2, 3], [4, 5, 6]]
Shallow Copy: [[99, 2, 3], [4, 5, 6]]
Deep Copy: [[99, 2, 3], [4, 88, 6]]


Original Array: [99  2  3]
Shallow Copy: [99  2  3]
Deep Copy: [99 88  3]


In [7]:
import numpy as np
arr = np.array([5, 10, 15, 20, 25]) 
a = arr[3] 
print(a)


20


In [9]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6])
sub_array = arr[:4] 
print(sub_array)


[1 2 3 4]


In [11]:
import numpy as np
arr = np.array([7, 8, 9, 10])  
reshaped_arr = arr.reshape(1, 4) 
print(reshaped_arr)
print("Shape of the array:", reshaped_arr.shape) 


[[ 7  8  9 10]]
Shape of the array: (1, 4)


In [33]:
import numpy as np
arr = np.array([11, 12, 13, 14])  

arr_2d = np.expand_dims(arr, axis=1) 

print(arr_2d)
print("Shape of the array:", arr_2d.shape) 


[[11]
 [12]
 [13]
 [14]]
Shape of the array: (4, 1)


In [27]:
import numpy as np
arr = np.array([12,24,36,48,60])
sub_array = arr[:4] 
sub_array[0]=99
print(sub_array)
print(arr)

[99 24 36 48]
[99 24 36 48 60]


In [29]:
import numpy as np

arr = np.array([1, 3, 5])
arr = np.append(arr, [2, 9])  
arr = np.insert(arr, 1, 4)   

print(arr)


[1 4 3 5 2 9]


In [43]:
a=10
b="sadam"
print(a , b)

10 sadam
