In [3]:
print(np.__version__)

1.26.4


In [1]:
import numpy as np

A=np.array([1,2,3])
A=A*5

print(A)

[ 5 10 15]
1.26.4


In [45]:
A=np.array("4")

B=np.array([1,2,3])

C=np.array([[1,2,3],[4,5,6],[7,8,9]])

D=np.array([[[1,2,3],[4,5,6],[7,8,9]],
            [[1,2,3],[4,5,6],[7,8,9]],
            [[1,"",3],[4,5,6],[7,8,""]]])

print(A)
print(B)
print(C)
print(D)

4
[1 2 3]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[['1' '2' '3']
  ['4' '5' '6']
  ['7' '8' '9']]

 [['1' '2' '3']
  ['4' '5' '6']
  ['7' '8' '9']]

 [['1' '' '3']
  ['4' '5' '6']
  ['7' '8' '']]]


In [47]:
# Dimention of array

A=np.array("4")

B=np.array([1,2,3])

C=np.array([[1,2,3],[4,5,6],[7,8,9]])

D=np.array([[[1,2,3],[4,5,6],[7,8,9]],
            [[1,2,3],[4,5,6],[7,8,9]],
            [[1,"",3],[4,5,6],[7,8,""]]])

print(A.ndim)
print(B.ndim)
print(C.ndim)
print(D.ndim)

0
1
2
3


In [53]:
# Shape of array

A=np.array("4")

B=np.array([1,2,3])

C=np.array([[1,2,3],[4,5,6],[7,8,9]])

D=np.array([[1,2,3],[7,8,9]])

E=np.array([[[1,2,3],[4,5,6],[7,8,9]],
            [[1,2,3],[4,5,6],[7,8,9]],
            [[1,"",3],[4,5,6],[7,8,""]]])

F=np.array([[[1,2,3],[4,5,6],[7,8,9]],
           [[1,"",3],[4,5,6],[7,8,""]]])

print(A.shape)
print(B.shape)
print(C.shape)
print(D.shape)
print(E.shape)
print(F.shape)

()
(3,)
(3, 3)
(2, 3)
(3, 3, 3)
(2, 3, 3)


In [63]:
A=np.array([[['a','b','c'],['d','e','f'],['g','h','i']],
            [['j','k','l'],['m','n','o'],['p','q','r']],
            [['s','t','u'],['v','w','x'],['y','z','']]])

#Chain indexing 
print(A[0][1][1])

#Multidimensional Indexing
print(A[0,1,1])

e
e


In [69]:
A=np.array([[['a','b','c'],['d','e','f'],['g','h','i']],
            [['j','k','l'],['m','n','o'],['p','q','r']],
            [['s','t','u'],['v','w','x'],['y','z','']]])

name= A[2,0,0] + A[0,0,0] + A[0,1,0] + A[0,0,0] + A[1,1,0]

print(name)

sadam


In [17]:
A = np.array([[1,2,3,4],
              [5,6,7,8],
              [9,10,11,12],
              [13,14,15,16]])

print(A[2])
print(A[-1]) # accessing last index


[ 9 10 11 12]
[13 14 15 16]


In [23]:
# Slicing

A = np.array([[1,2,3,4],
              [5,6,7,8],
              [9,10,11,12],
              [13,14,15,16]])

#array[start:end:step]
print(A[0:3:2]) # start from index 0 juntil 3 which is exclusive with two step jumps

[[ 1  2  3  4]
 [ 9 10 11 12]]


In [25]:
# Slicing

A = np.array([[1,2,3,4],
              [5,6,7,8],
              [9,10,11,12],
              [13,14,15,16]])

#array[start:end:step]
print(A[1:]) # start from index 1 until end

[[ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [31]:
# Slicing

A = np.array([[1,2,3,4],
              [5,6,7,8],
              [9,10,11,12],
              [13,14,15,16]])

#array[start:end:step]
print(A[::2]) #print whole array with 2 step jumps

[[ 1  2  3  4]
 [ 9 10 11 12]]


In [33]:
# Slicing 

A = np.array([[1,2,3,4],
              [5,6,7,8],
              [9,10,11,12],
              [13,14,15,16]])

#array[start:end:step]
print(A[::-1]) #rows reversed

[[13 14 15 16]
 [ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]


In [35]:
# Slicing 

A = np.array([[1,2,3,4],
              [5,6,7,8],
              [9,10,11,12],
              [13,14,15,16]])

#array[start:end:step]
print(A[::-2]) #rows reversed with two steps jumps

[[13 14 15 16]
 [ 5  6  7  8]]


In [49]:
# column selection

A = np.array([[1,2,3,4],
              [5,6,7,8],
              [9,10,11,12],
              [13,14,15,16]])

print(A[:,2]) #select column at index 2

print(A[:,-1]) #select column at the end

[ 3  7 11 15]
[ 4  8 12 16]


In [53]:
# Slicing 

A = np.array([[1,2,3,4],
              [5,6,7,8],
              [9,10,11,12],
              [13,14,15,16]])

#array[start:end:step]
print(A[:,0:3])  # print column from index 0 to 3 (exclusive)

[[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]
 [13 14 15]]


In [55]:
# Slicing 

A = np.array([[1,2,3,4],
              [5,6,7,8],
              [9,10,11,12],
              [13,14,15,16]])

#array[start:end:step]
print(A[:,1:])  # print all columns except first

[[ 2  3  4]
 [ 6  7  8]
 [10 11 12]
 [14 15 16]]


In [59]:
# Slicing 

A = np.array([[1,2,3,4],
              [5,6,7,8],
              [9,10,11,12],
              [13,14,15,16]])

#array[start:end:step]
print(A[:,1::2])  # selecting every second column by adding the step

[[ 2  4]
 [ 6  8]
 [10 12]
 [14 16]]


In [63]:
# Slicing 

A = np.array([[1,2,3,4],
              [5,6,7,8],
              [9,10,11,12],
              [13,14,15,16]])

#array[start:end:step]
print(A[:,::-1])  # reversing order of the columns

[[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]
 [16 15 14 13]]
[[ 4  2]
 [ 8  6]
 [12 10]
 [16 14]]


In [71]:
# Slicing 
#combining both rows and column selection

A = np.array([[1,2,3,4],
              [5,6,7,8],
              [9,10,11,12],
              [13,14,15,16]])

#array[start:end:step]
print(A[0:2,0:2])  # reversing order of the columns
print ("another example")
print(A[2:,2:])


[[1 2]
 [5 6]]
another example
[[11 12]
 [15 16]]


In [77]:
# Arithmetic

# Scalar Arithmetic (scalar is a single value)

array = np.array([1,2,3,4])

print(array+1)
print(array-2)
print(array*3)
print(array/4)
print(array**5)

[2 3 4 5]
[-1  0  1  2]
[ 3  6  9 12]
[0.25 0.5  0.75 1.  ]
[   1   32  243 1024]


In [87]:
# vectorize math functions (vector is a single dimension)

array = np.array([1.11, 2.5, 3.89, 4.6])

print(np.sqrt(array))
print(np.round(array))
print(np.floor(array))
print(np.ceil(array))
print(np.pi)


[1.05356538 1.58113883 1.97230829 2.14476106]
[1. 2. 4. 5.]
[1. 2. 3. 4.]
[2. 3. 4. 5.]
3.141592653589793


In [89]:
#Exaecise

radii = np.array([1, 2, 3, 4])

# area of each radius
print(np.pi*radii**2) 

[ 3.14159265 12.56637061 28.27433388 50.26548246]


In [95]:
# element wise arithematic

A = np.array([1,2,3,4])
B = np.array([1,2,3,4])

print(A+B)
print(A-B)
print(A*B)
print(A/B)
print(A**B)

[2 4 6 8]
[0 0 0 0]
[ 1  4  9 16]
[1. 1. 1. 1.]
[  1   4  27 256]


In [105]:
#comparison operator

scores = np.array([44,55,88,99,100])

print(scores)
print(scores == 100)
print(scores < 60)
scores[scores<60] = 0
print(scores)



[ 44  55  88  99 100]
[False False False False  True]
[ True  True False False False]
[  0   0  88  99 100]


In [111]:
# Broadcasting allows Numpy to performs operations on array
# with different shapes by virtual expanding dimensions
# so they match the large array shape

# The dimension have the same size
# OR
# one of the dimension has a size of 1

array1 = np.array([[1,2,3,4]])
array2 = np.array([[1],[2],[3],[4]])

print(array1.shape)
print(array2.shape)

(1, 4)
(4, 1)


In [113]:
# Broadcasting

array1 = np.array([[1,2,3,4]])
array2 = np.array([[1],[2],[3],[4]])

print(array1*array2)

[[ 1  2  3  4]
 [ 2  4  6  8]
 [ 3  6  9 12]
 [ 4  8 12 16]]


In [117]:
array1 = np.array([[1,2,3,4,5,6,7,8,9,10]])
array2 = np.array([[1],[2],[3],[4],[5],[6],[7],[8],[9],[10]])

print("Multplication Table is:")
print (array1*array2)


Multplication Table is:
[[  1   2   3   4   5   6   7   8   9  10]
 [  2   4   6   8  10  12  14  16  18  20]
 [  3   6   9  12  15  18  21  24  27  30]
 [  4   8  12  16  20  24  28  32  36  40]
 [  5  10  15  20  25  30  35  40  45  50]
 [  6  12  18  24  30  36  42  48  54  60]
 [  7  14  21  28  35  42  49  56  63  70]
 [  8  16  24  32  40  48  56  64  72  80]
 [  9  18  27  36  45  54  63  72  81  90]
 [ 10  20  30  40  50  60  70  80  90 100]]


In [123]:
#Aggregate Functions = sumarrize data and typically returns a single value

array = np.array([[1,2,3,4,5],
                  [6,7,8,9,10]])

print(np.sum(array))
print(np.mean(array))
print(np.std(array))
print(np.var(array))
print(np.min(array))
print(np.max(array))
print(np.argmin(array)) #return position of minimun value
print(np.argmax(array)) #return position of maximum value



55
5.5
2.8722813232690143
8.25
1
10
0
9


In [129]:
#Aggregate Functions = sumarrize data and typically returns a single value

array = np.array([[1,2,3,4,5],
                  [6,7,8,9,10]])

print(np.sum(array))
print(np.sum(array,axis=0)) # column wise sum
print(np.sum(array,axis=1)) # row wise sum

55
[ 7  9 11 13 15]
[15 40]


In [145]:
# Filtering = refers to the process of selection elements from array that mactches a given condition

ages = np.array([[21,12,19,14,65],
                  [16,17,18,55,10]])

teenagers = ages[ages<18]

#logical operator 'and' uses by python but '&' uses in numpy
adults = ages[(ages>=18) & (ages<65)]

#logical operator 'or' uses by python but '|' uses in numpy
not_adults = ages[(ages<18) | (ages>=65)]



print(teenagers) # answer will be in boolean indexing form , answer will be in a vector form
print(adults)
print(not_adults)

[12 14 16 17 10]
[21 19 18 55]
[12 14 65 16 17 10]


In [147]:
# Filtering 

ages = np.array([[21,12,19,14,65],
                  [16,17,18,55,10]])

seniors = ages[ages>=60]
evens = ages[ages%2==0]
odds = ages[ages%2!=0]

print(seniors)
print(evens)
print(odds)

# boolean indexing will flaten your data but its very faster than 'where' function discuss below

[65]
[12 14 16 18 10]
[21 19 65 17 55]


In [161]:
# filtering while reserving orignal shape we use 'where' clause

numbers = np.array([[21,12,19,14,65],
                  [16,17,18,55,10]])

# numpy.where(condition , array , fill value)
adults = np.where(numbers>=18,numbers,'+')
print(adults)

fail = np.where(numbers<35,numbers,0)
print(fail)

# where function will keep your original array shape but its alot slower than using boolean indexing

[['21' '+' '19' '+' '65']
 ['+' '+' '18' '55' '+']]
[[21 12 19 14  0]
 [16 17 18  0 10]]


In [219]:
# Random numbers = useful for simulations , modeling , applying random transformations and testing purposes

rng = np.random.default_rng()
#random number between 1 and 6
print(rng.integers(1,7)) # second number is exclusive
#OR
print(rng.integers(low=1,high=7)) # second number is exclusive
print(rng.integers(low=1,high=101)) # second number is exclusive


2
1
52


In [231]:
rng = np.random.default_rng()

print(rng.integers(1,101,3))
#OR
print(rng.integers(low=1, high=101, size=3))

[82 30 22]
[45 40 28]


In [237]:
rng = np.random.default_rng()

print(rng.integers(low=1, high=101, size=(3,2))) #3 rows and 2 columns

[[81 13]
 [69 98]
 [87 66]]


In [245]:
# if you want to generate same random numbers then use user define 'seed' value

rng = np.random.default_rng(seed=1) # settinig seed id useful if you need to produce the  same results

print(rng.integers(low=1, high=101, size=(3,2)))

[[48 52]
 [76 96]
 [ 4 15]]


In [253]:
# random floating point numbers

print(np.random.uniform(low=-1,high=1))
print(np.random.uniform(low=-1,high=1,size=3))

-0.8105291003475021
[-0.81392251  0.17959667  0.54583089]


In [261]:
print(np.random.uniform(low=-1,high=1,size=(4,4))) #4rows 4columns

[[-0.1653904   0.11737966 -0.71922612 -0.60379702]
 [ 0.60148914  0.93652315 -0.37315164  0.38464523]
 [ 0.7527783   0.78921333 -0.82991158 -0.92189043]
 [-0.66033916  0.75628501 -0.80330633 -0.15778475]]


In [259]:
# setting seed

np.random.seed(seed=1)
print(np.random.uniform(low=-1,high=1,size=(4,4))) #4rows 4columns

#we can reproduce the same values by using the same seed


[[-0.16595599  0.44064899 -0.99977125 -0.39533485]
 [-0.70648822 -0.81532281 -0.62747958 -0.30887855]
 [-0.20646505  0.07763347 -0.16161097  0.370439  ]
 [-0.5910955   0.75623487 -0.94522481  0.34093502]]


In [269]:
# shuffling array
array= np.array([1,2,3,4,5])
# first create an rng object , then call its shuffle method
rng = np.random.default_rng()
rng.shuffle(array)

print(array)

[1 5 4 2 3]


In [275]:
# selecting random items from an array
fruits = np.array(["apple","mango","banana","orange","grapes","coconut","pineapple"])

# first create an rng object , then call its choice method
rng = np.random.default_rng()
fruits = rng.choice(fruits ,size=3) #3 random selections

print(fruits)

['apple' 'grapes' 'mango']


In [277]:
# selecting random items from an array
fruits = np.array(["apple","mango","banana","orange","grapes","coconut","pineapple"])

# first create an rng object , then call its choice method
rng = np.random.default_rng()
fruits = rng.choice(fruits ,size=(3,3)) #3x3 random selections

print(fruits)

[['apple' 'coconut' 'grapes']
 ['apple' 'grapes' 'banana']
 ['grapes' 'grapes' 'mango']]


In [287]:
# selecting random items from an array
fruits = np.array(["🍎","🥭","🍌","🍊","🍇","🥥","🍍"])

# first create an rng object , then call its choice method
rng = np.random.default_rng()
fruits = rng.choice(fruits ,size=(3,3)) #3x3 random selections

print(fruits)

[['🍊' '🍎' '🥥']
 ['🥭' '🍊' '🍎']
 ['🍇' '🍇' '🥭']]


In [3]:
import numpy as np

# Define two 2x2 matrices
A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])

# Element-wise multiplication
elementwise = A * B

# Matrix multiplication (dot product)
dot_product = np.dot(A, B)      # or A @ B

# Matrix multiplication using matmul
matmul_product = np.matmul(A, B)

# Display results
print("Matrix A:\n", A)
print("Matrix B:\n", B)
print("\n Element-wise multiplication:\n", elementwise)
print("\n Matrix multiplication using np.dot:\n", dot_product)
print("\n Matrix multiplication using np.matmul:\n", matmul_product)


Matrix A:
 [[1 2]
 [3 4]]
Matrix B:
 [[5 6]
 [7 8]]

 Element-wise multiplication:
 [[ 5 12]
 [21 32]]

 Matrix multiplication using np.dot:
 [[19 22]
 [43 50]]

 Matrix multiplication using np.matmul:
 [[19 22]
 [43 50]]


In [1]:
import numpy as np

# Create a matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6]])

# Transpose
transpose_matrix = matrix.T

print(transpose_matrix)


[[1 4]
 [2 5]
 [3 6]]
